#### **Задание 1**
Создайте numpy array с элементами от числа N до 0

(например, для `N = 10` это будет array`([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])`).

In [5]:
import numpy as np

N = input('Введите количество элементов массива: ')
N = int(N)
x = np.arange(N-1, -1, -1)
print(x)

Введите количество элементов массива:  5


[4 3 2 1 0]


#### **Задание 2**
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [9]:
import numpy as np

N = input('Введите количество элементов матрицы: ')
N = int(N)

one      = np.eye(N)
diag     = np.arange(N-1, -1, -1)
m        = one * diag 
diag_sum = np.sum(diag)

print(m)
print('Сумма элементов диагонали матрицы: ', diag_sum)

Введите количество элементов матрицы:  6


[[5. 0. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
Сумма элементов диагонали матрицы:  15


#### **Задание 3**
Решите систему уравнений: 

`4x + 2y + z = 4`

`x + 3y = 12`

`5y + 4z = -3`

In [12]:
import numpy as np
from numpy import linalg

l = np.array([[4, 2, 1],[1, 3, 0],[0, 5, 4]])
r = np.array([4, 12, -3])
solve = linalg.solve(l,r)
print(solve)

[ 0.46666667  3.84444444 -5.55555556]


In [13]:
4*0.46666667 + 2*  3.84444444 -5.55555556    

4.0

In [14]:
0.46666667 + 3*3.84444444

11.999999990000001

In [18]:
5*3.84444444 -4*5.55555556

-3.0000000399999998